name: Build

on:
    push:
        branches:
            - main
        paths:
            - 'isip/**'

jobs:
    build-isip:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Build on merge
              run: |
                  cd isip
                  echo "installing dependencies"
                  echo "Building isip"

    build-onead_lib:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Build on merge
              run: |
                  cd onead_lib
                  echo "installing dependencies"
                  echo "Building onead-lib"
