name: Build

on:
    push:
        branches:
            - main
        paths:
            - 'isip/**'

jobs:
    build-isip:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - uses: dorny/paths-filter@v3
              id: changes
              with:
                filters: |
                    src:
                      - 'isip/**'
            - name: Build on merge
              if: steps.changes.outputs.src == 'true'
              run: |
                  cd isip
                  echo "installing dependencies"
                  echo "Building isip"

    build-onead_lib:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - uses: dorny/paths-filter@v3
              id: changes
              with:
                filters: |
                    src:
                      - 'onead_lib/**'

            - name: Build on merge
              if: steps.changes.outputs.src == 'true'
              run: |
                  cd onead_lib
                  echo "installing dependencies"
                  echo "Building onead-lib"
