name: Build

on:
    push:
        branches:
            - main

jobs:
    isip-diff:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - uses: dorny/paths-filter@v3
              id: changes
              with:
                filters: |
                    src:
                      - 'isip/**'
            - name: record changes
              if: steps.changes.outputs.src == 'true'
              run: echo "BUILD_ISIP=true" >> "$GITHUB_ENV"
        outputs:
            BUILD_ISIP: ${{ env.BUILD_ISIP }}

    onead_lib-diff:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - uses: dorny/paths-filter@v3
              id: changes
              with:
                filters: |
                    src:
                      - 'onead_lib/**'

            - name: record changes
              if: steps.changes.outputs.src == 'true'
              run: echo "BUILD_ONEADLIB=true" >> "$GITHUB_ENV"
        outputs:
            BUILD_ONEADLIB: ${{ env.BUILD_ISIP }}
    player-diff:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - uses: dorny/paths-filter@v3
              id: changes
              with:
                filters: |
                    src:
                      - 'oneplayer/**'
            - name: record changes
              if: steps.changes.outputs.src == 'true'
              run: echo "BUILD_ONEPLAYER=true" >> "$GITHUB_ENV"
        outputs:
            BUILD_ONEPLAYER: ${{ env.BUILD_ONEPLAYER }}

    build:
        runs-on: ubuntu-latest
        if: ${{ always() }}
        needs: [isip-diff, onead_lib-diff, player-diff]
        env:
            BUILD_ISIP: ${{ needs.isip-diff.outputs.BUILD_ISIP }}
            BUILD_ONEADLIB: ${{ needs.onead_lib-diff.outputs.BUILD_ONEADLIB }}
            BUILD_ONEPLAYER: ${{ needs.player-diff.outputs.BUILD_ONEPLAYER }}
            ISIP_DIR: 'isip'
            ONEADLIB_DIR: 'onead_lib'
            PLAYER_DIR: 'oneplayer'
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                node-version: '18'
            - name: build isip
              if: ${{ env.BUILD_ISIP == 'true' }}
              run: |
                cd $ISIP_DIR
                npm install
                npm run build
            - name: build onead_lib
              if: ${{ env.BUILD_ONEADLIB == 'true' }}
              run: |
                cd $ONEADLIB_DIR
                npm install
                npm run build
            - name: build oneplayer
              if: ${{ env.BUILD_ONEPLAYER == 'true' }}
              run: |
                cd $PLAYER_DIR
                npm install
                npm run build
            - name: Upload build artifacts
              uses: actions/upload-artifact@v3
              with:
                name: build-artifacts
                path: |
                  ${{ env.ISIP_DIR }}/dist
                  ${{ env.ONEADLIB_DIR }}/dist
                  ${{ env.PLAYER_DIR }}/dist
    deploy:
        needs: build  # 確保在建置作業完成後執行
        runs-on: ubuntu-latest
        steps:
          - name: Download build artifacts
            uses: actions/download-artifact@v3
            with:
              name: build-artifacts
              path: dist

          - name: Deploy
            run: |
              # 這裡放置您的部署指令
              echo "Deploying builds from dist directory"
