name: Build on Merge and Player Changes

on:
    push:
        branches:
            - main
        paths:
            - 'oneplayer/**'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Build on merge
              run: |
                  cd oneplayer
                  echo "installing dependencies"
                  echo "Building player"
