name: Generate Changelog
on:
  workflow_run:        # 可以加入這個觸發條件
    workflows: [Build]  # 部署工作流程的名稱
    types:
      - completed
jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate changelog
        run: |
          BANNER_INFO=""

          # commit history
          COMMITS_INFO=$(git log ${{ github.event.before }}..HEAD --format="%s@%an" | sort -u)
          echo "=== Commit History ==="
          echo "$COMMITS_INFO"

          # banner
          for file in $CHANGED_FILES; do
            if [ -f "$file" ]; then
              banner=$(head -n 1 "$file")
              BANNER_INFO+="$banner"$'\n'
            fi
          done

          # build changelog
          CHANGELOG_MD=$(cat << 'EOF'
          ## Version
          \`\`\`
          $BANNER_INFO
          \`\`\`

          ## Commit History
          $COMMITS_INFO

          ## JIRA
          JIRA url
          EOF
          )