name: Generate Changelog
on:
  workflow_run:
    workflows: [Build]
    types:
      - completed
jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: 'production'
          fetch-depth: 0

      - name: Generate changelog
        run: |
          BANNER_INFO=""

          # 取得最後一次 release tag
          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          echo "LAST_TAG: $LAST_TAG"

          if [ -z "$LAST_TAG" ]; then
            # 沒有 tag 的情況
            COMMITS_INFO=$(git log --format="%s@%an" | sort -u)
            CHANGED_FILES=$(git diff --name-only $(git rev-list --max-parents=0 HEAD) HEAD | grep "guoshipartners/static/js/.*\.js$" || true)
          else
            # 有 tag 的情況
            COMMITS_INFO=$(git log ${LAST_TAG}..HEAD --format="%s@%an" | sort -u)
            CHANGED_FILES=$(git diff --name-only ${LAST_TAG} HEAD | grep "guoshipartners/static/js/.*\.js$" || true)
          fi

          # 格式化輸出變更檔案
          echo "## Version"
          echo "```"
          $(for file in $CHANGED_FILES; do
            if [ -f "$file" ]; then
              banner=$(head -n 1 "$file")
              echo "$banner"+"\n"
            fi
          done)
          echo "```"

          # 格式化輸出提交信息
          echo "## What's Changed"
          echo "$COMMITS_INFO" | while IFS= read -r line; do
            echo "* $line"
          done